### PR TITLE
Basic eslint configuration and example usage

### PR DESCRIPTION
**Pull request by tannerljohnson**
finishes #100 

I installed eslint using the docs you linked to @eparadise https://eslint.org/docs/user-guide/getting-started
I think your screenshot doesn't show the file (which was probably created successfully) because it's appended with a period like `.eslintrc.js`. Finder hides these files unfortunately :/ 

This is a very basic installation that uses airbnb's rules (sort of an industry standard)
I followed the docs and applied the lint to `About.js`
```
npx eslint app/javascript/components/About.js
```
and then
```
npx eslint app/javascript/components/About.js --fix
```
to fix

A few ideas to move forward:
* run this command as a pre-commit hook on all staged files you've touched
* start going through all files and applying rules
* consider looking into more advanced configuration stuff (not sure what that entails)

### CODE REVIEW

**Comment by eparadise** [comment]
Is there a command I need to run to configure eslint locally? When I tried "npx eslint app/javascript/components/CurriculumCard.js", I got the following error:

Screen Shot 2020-06-09 at 12 53 26 PM

**Comment by eparadise** [comment]
Also, I had some additional ideas for ESLint configuration. Should I do those in a separate PR, or push them up to this branch? I wanted to install Prettier and also add some scripts to package.json to make it easier to run lint commands. I also wanted to add "eslint:recommended" to the extensions in .eslintrc.js.

**Comment by tannerljohnson** [comment]
> Is there a command I need to run to configure eslint locally? When I tried "npx eslint app/javascript/components/CurriculumCard.js", I got the following error:
> 
> Screen Shot 2020-06-09 at 12 53 26 PM

hmmm i think you may need to run `yarn install` again?

**Comment by tannerljohnson** [comment]
> Also, I had some additional ideas for ESLint configuration. Should I do those in a separate PR, or push them up to this branch? I wanted to install Prettier and also add some scripts to package.json to make it easier to run lint commands. I also wanted to add "eslint:recommended" to the extensions in .eslintrc.js.

ooooh love those ideas! i think we should merge this first and then add those changes in a separate PR :) when you're ready, can you approve this PR @eparadise so we can merge?

**Pull request merged**
